# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tess < Formula
  desc "Generate Lattice review summaries; optional Drive upload via rclone."
  homepage "https://github.com/vigetlabs/tess"
  version "0.1.2"

  depends_on "pandoc"
  depends_on "rclone"
  depends_on "tectonic"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/vigetlabs/tess/releases/download/v0.1.2/tess_darwin_arm64_v0.1.2.tar.gz"
    sha256 "8ab3dac66f388f838430423be8ec37d22619cca212f40e9971cce7cc9916734e"

    def install
      bin.install "tess"
    end
  end

  test do
    system "#{bin}/tess", "--help"
  end
end
