# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tess < Formula
  desc "Generate Lattice review summaries; optional Drive upload via rclone."
  homepage "https://github.com/vigetlabs/tess"
  version "0.1.1"

  depends_on "pandoc"
  depends_on "rclone"
  depends_on "tectonic"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/vigetlabs/tess/releases/download/v0.1.1/tess_darwin_arm64_v0.1.1.tar.gz"
    sha256 "b0fd17e4c510d85902e829d863def93c50048f7cb66f19f7ed8fe757963028a9"

    def install
      bin.install "tess"
    end
  end

  test do
    system "#{bin}/tess", "--help"
  end
end
